// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTdRZHnZtcTFcdXGBjtoDChhy6HFC6Sw',
    appId: '1:795948098638:android:17f0380fa3121166da0f1f',
    messagingSenderId: '795948098638',
    projectId: 'drivebuddy-6c4b6',
    storageBucket: 'drivebuddy-6c4b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_NARy34C1JVpjBzIJZYlnNfFCoz8UJw',
    appId: '1:795948098638:ios:d2fdf1e75f217117da0f1f',
    messagingSenderId: '795948098638',
    projectId: 'drivebuddy-6c4b6',
    storageBucket: 'drivebuddy-6c4b6.firebasestorage.app',
    iosBundleId: 'com.example.drivebuddy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAId8xNvf--jvYxdmCllBX-7N_qD6eAmDc',
    appId: '1:795948098638:web:cc8f6c6a279cf120da0f1f',
    messagingSenderId: '795948098638',
    projectId: 'drivebuddy-6c4b6',
    authDomain: 'drivebuddy-6c4b6.firebaseapp.com',
    storageBucket: 'drivebuddy-6c4b6.firebasestorage.app',
  );

}